"""
GLOBAL SETTINGS AND ENVIRONMENT VARIABLE CONFIGURATIONS DEFINING LIMITS AND LOCALE SETTINGS.
"""

import os
from dotenv import load_dotenv

# LOAD DEFAULTS FROM .ENV IF AVAILABLE
load_dotenv()

# MAXIMUM ALLOCATED BYTE SIZE PER FILE TO PREVENT OOM FAULTS
MAX_FILE_SIZE: int = int(os.getenv("PROMPTIFY_MAX_FILE_SIZE", 5 * 1024 * 1024))

# MAXIMUM NUMBER OF FILE DESCRIPTORS AIOFILES IS ALLOWED TO HOLD CONCURRENTLY
MAX_CONCURRENT_READS: int = int(os.getenv("PROMPTIFY_MAX_CONCURRENT_READS", 100))

# REGIONAL FALLBACK LOCALE FOR THE I18N MODULE
LOCALE: str = os.getenv("PROMPTIFY_LOCALE", "en")
